### PR TITLE
update de, en_us and fr patterns

### PR DESCRIPTION
**Pull request by doits**
I update the patterns of the languages by replacing the patterns with the ones from http://tug.org/svn/texhyphen/trunk/hyph-utf8/tex/generic/hyph-utf8/patterns/txt/.

I am not sure if this everything needed to do?

### CODE REVIEW

**Comment by doits** [comment]
The test must be refactored/updated for newer ruby versions ... but everything else should work afaik.

**Comment by halostatue** [comment]
Thanks! I will look at trying to get the infrastructure up to date.

**Comment by gr8bit** [comment]
👍

**Comment by halostatue** [comment]
This will be closed by #21. Thank you for your contribution!

**Pull request closed without merging**
